name: Build and Deploy to PyPI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: make install

      - name: Run Linter
        run: make lint

      - name: Run Tests
        run: make test

      - name: Build Package
        run: make build

      - name: Publish to PyPI
        if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/heads/master')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
